CREATE TABLE CardFormat(
	CardFormatId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	FormatId UNIQUEIDENTIFIER,
	CardId UNIQUEIDENTIFIER,
	FOREIGN KEY (FormatId) REFERENCES FormatType(TypeId),
	FOREIGN KEY (CardId) REFERENCES PokemonCard(CardId)
)